package org.eclipse.xtext.xtext.ui.editor.contentassist.flaky;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(Suite.class)
@SuiteClasses({
	XtextContentAssistTestSubclass1.class,
	XtextContentAssistTestSubclass2.class,
	XtextContentAssistTestSubclass3.class,
	XtextContentAssistTestSubclass4.class,
	XtextContentAssistTestSubclass5.class,
	XtextContentAssistTestSubclass6.class,
	XtextContentAssistTestSubclass7.class,
	XtextContentAssistTestSubclass8.class,
	XtextContentAssistTestSubclass9.class,
	XtextContentAssistTestSubclass10.class,
	XtextContentAssistTestSubclass11.class,
	XtextContentAssistTestSubclass12.class,
	XtextContentAssistTestSubclass13.class,
	XtextContentAssistTestSubclass14.class,
	XtextContentAssistTestSubclass15.class,
	XtextContentAssistTestSubclass16.class,
//	XtextContentAssistTestSubclass17.class,
//	XtextContentAssistTestSubclass18.class,
//	XtextContentAssistTestSubclass19.class,
//	XtextContentAssistTestSubclass20.class,
//	XtextContentAssistTestSubclass21.class,
//	XtextContentAssistTestSubclass22.class,
//	XtextContentAssistTestSubclass23.class,
//	XtextContentAssistTestSubclass24.class,
//	XtextContentAssistTestSubclass25.class,
//	XtextContentAssistTestSubclass26.class,
//	XtextContentAssistTestSubclass27.class,
//	XtextContentAssistTestSubclass28.class,
//	XtextContentAssistTestSubclass29.class,
//	XtextContentAssistTestSubclass30.class,
//	XtextContentAssistTestSubclass31.class,
//	XtextContentAssistTestSubclass32.class,
//	XtextContentAssistTestSubclass33.class,
//	XtextContentAssistTestSubclass34.class,
//	XtextContentAssistTestSubclass35.class,
//	XtextContentAssistTestSubclass36.class,
//	XtextContentAssistTestSubclass37.class,
//	XtextContentAssistTestSubclass38.class,
//	XtextContentAssistTestSubclass39.class,
//	XtextContentAssistTestSubclass40.class,
//	XtextContentAssistTestSubclass41.class,
//	XtextContentAssistTestSubclass42.class,
//	XtextContentAssistTestSubclass43.class,
//	XtextContentAssistTestSubclass44.class,
//	XtextContentAssistTestSubclass45.class,
//	XtextContentAssistTestSubclass46.class,
//	XtextContentAssistTestSubclass47.class,
//	XtextContentAssistTestSubclass48.class,
//	XtextContentAssistTestSubclass49.class,
//	XtextContentAssistTestSubclass50.class,
//	XtextContentAssistTestSubclass51.class,
//	XtextContentAssistTestSubclass52.class,
//	XtextContentAssistTestSubclass53.class,
//	XtextContentAssistTestSubclass54.class,
//	XtextContentAssistTestSubclass55.class,
//	XtextContentAssistTestSubclass56.class,
//	XtextContentAssistTestSubclass57.class,
//	XtextContentAssistTestSubclass58.class,
//	XtextContentAssistTestSubclass59.class,
//	XtextContentAssistTestSubclass60.class,
//	XtextContentAssistTestSubclass61.class,
//	XtextContentAssistTestSubclass62.class,
//	XtextContentAssistTestSubclass63.class,
//	XtextContentAssistTestSubclass64.class,
//	XtextContentAssistTestSubclass65.class,
//	XtextContentAssistTestSubclass66.class,
//	XtextContentAssistTestSubclass67.class,
//	XtextContentAssistTestSubclass68.class,
//	XtextContentAssistTestSubclass69.class,
//	XtextContentAssistTestSubclass70.class,
//	XtextContentAssistTestSubclass71.class,
//	XtextContentAssistTestSubclass72.class,
//	XtextContentAssistTestSubclass73.class,
//	XtextContentAssistTestSubclass74.class,
//	XtextContentAssistTestSubclass75.class,
//	XtextContentAssistTestSubclass76.class,
//	XtextContentAssistTestSubclass77.class,
//	XtextContentAssistTestSubclass78.class,
//	XtextContentAssistTestSubclass79.class,
//	XtextContentAssistTestSubclass80.class,
//	XtextContentAssistTestSubclass81.class,
//	XtextContentAssistTestSubclass82.class,
//	XtextContentAssistTestSubclass83.class,
//	XtextContentAssistTestSubclass84.class,
//	XtextContentAssistTestSubclass85.class,
//	XtextContentAssistTestSubclass86.class,
//	XtextContentAssistTestSubclass87.class,
//	XtextContentAssistTestSubclass88.class,
//	XtextContentAssistTestSubclass89.class,
//	XtextContentAssistTestSubclass90.class,
//	XtextContentAssistTestSubclass91.class,
//	XtextContentAssistTestSubclass92.class,
//	XtextContentAssistTestSubclass93.class,
//	XtextContentAssistTestSubclass94.class,
//	XtextContentAssistTestSubclass95.class,
//	XtextContentAssistTestSubclass96.class,
//	XtextContentAssistTestSubclass97.class,
//	XtextContentAssistTestSubclass98.class,
//	XtextContentAssistTestSubclass99.class,
//	XtextContentAssistTestSubclass100.class
})
public class XtextContentAssistTestSuite {
}
