name: Build

on:
  push:
    branches: ['*'] # Run on any pushed branch, but not on any pushed tag
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.base.repo.clone_url != github.event.pull_request.head.repo.clone_url
    name: ${{ matrix.os }}, Java-${{ matrix.jdkVersion }}, Eclipse ${{ matrix.targetPlatform }}
    strategy:
      matrix:
        os: ['ubuntu', 'macos' ] # 'windows-latest' too flaky
        jdkVersion: ['11', '17']
        targetPlatform: ['r202203', 'latest'] # Only test latest and earliest platform
        exclude: # Since Eclipse 2023-06 Java17 is required
          - jdkVersion: 11
            targetPlatform: latest
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: |
            11
            17
          distribution: 'temurin'

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test
        uses: coactions/setup-xvfb@v1
        with: 
          run: "mvn clean verify --batch-mode --toolchains ../releng/toolchains.xml -PuseJenkinsSnapshots,strict-release-jdk \
            -Dtoolchain.jdk=${{ matrix.jdkVersion }} -Dtarget-platform-classifier=xtext-${{ matrix.targetPlatform }}"
          working-directory: org.eclipse.xtext.full.releng

  build-maven-artifacts:
    if: github.event_name != 'pull_request' || github.event.pull_request.base.repo.clone_url != github.event.pull_request.head.repo.clone_url
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build Maven artifacts
        run: mvn clean verify --batch-mode -PuseJenkinsSnapshots
        working-directory: org.eclipse.xtext.maven.releng
