name: Build

on:
  push:
    branches: ['*'] # Run on any pushed branch, but not on any pushed tag
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.base.repo.clone_url != github.event.pull_request.head.repo.clone_url
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest' ] # 'windows-latest' too flaky
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test
        uses: coactions/setup-xvfb@v1
        with: 
          run: ./mvnw clean verify -PuseJenkinsSnapshots -f org.eclipse.xtext.full.releng

  build-maven-artifacts:
    if: github.event_name != 'pull_request' || github.event.pull_request.base.repo.clone_url != github.event.pull_request.head.repo.clone_url
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build Maven artifacts
        run: ./mvnw clean verify -PuseJenkinsSnapshots -f org.eclipse.xtext.maven.releng
